spring:
  application:
    name: edustream-ums-web-bff
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8081  # BFF runs on port 8081 (backend on 8080)

  servlet:
    context-path: /bff
    # Set the Context path

# Backend services configuration
services:

  student:
    url: http://localhost:8082/student
    api:
      test: /api/test

  course:
    url: http://localhost:8083/course
    api:
      test: /api/test

